[build]
  publish = "."
  command = "echo 'No build required - static site'"

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy-policy.html"
  status = 200

[[redirects]]
  from = "/terms-of-service"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms-of-service.html"
  status = 200

[[redirects]]
  from = "/support"
  to = "/#contact"
  status = 200

[[redirects]]
  from = "/help"
  to = "/#help"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404